In [1]:
import numpy as np

## BROADCAST

### fare operazioni matematiche tra array *di stesse dimensioni*

In [5]:
array1 = np.array([1,2,3,4,5])
array1 * 2

array([ 2,  4,  6,  8, 10])

In [6]:
np.exp(array1)    #ha elevato "e" per ciascun membro dell'array (e^1, e^2, e^3,...)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [8]:
np.sqrt(array1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [9]:
array2 = np.array([-1,-2,-3,-4,-5])
array2

array([-1, -2, -3, -4, -5])

In [11]:
array1 * array2

array([ -1,  -4,  -9, -16, -25])

In [12]:
array1 + array2

array([0, 0, 0, 0, 0])

In [18]:
matrice1 = np.ones((5,5))
matrice2 = np.random.uniform(0,1,(5,5))
matrice2

array([[0.78394456, 0.85006976, 0.06563672, 0.85537163, 0.99370784],
       [0.79073989, 0.14035838, 0.2386784 , 0.41615367, 0.98005121],
       [0.71230178, 0.75461153, 0.26182831, 0.86636747, 0.58519063],
       [0.58565055, 0.51511799, 0.56542451, 0.82693127, 0.39027079],
       [0.77255086, 0.24419654, 0.32537626, 0.29066956, 0.78334622]])

In [19]:
matrice1 + matrice2

array([[1.78394456, 1.85006976, 1.06563672, 1.85537163, 1.99370784],
       [1.79073989, 1.14035838, 1.2386784 , 1.41615367, 1.98005121],
       [1.71230178, 1.75461153, 1.26182831, 1.86636747, 1.58519063],
       [1.58565055, 1.51511799, 1.56542451, 1.82693127, 1.39027079],
       [1.77255086, 1.24419654, 1.32537626, 1.29066956, 1.78334622]])

In [20]:
matrice1 * matrice2

array([[0.78394456, 0.85006976, 0.06563672, 0.85537163, 0.99370784],
       [0.79073989, 0.14035838, 0.2386784 , 0.41615367, 0.98005121],
       [0.71230178, 0.75461153, 0.26182831, 0.86636747, 0.58519063],
       [0.58565055, 0.51511799, 0.56542451, 0.82693127, 0.39027079],
       [0.77255086, 0.24419654, 0.32537626, 0.29066956, 0.78334622]])

In [25]:
matrice1 = np.ones((5,5))
matrice2 = np.random.uniform(0,1,(5,1))
matrice2

array([[0.59744711],
       [0.3614434 ],
       [0.78192408],
       [0.26456425],
       [0.07249806]])

In [26]:
matrice1 + matrice2

array([[1.59744711, 1.59744711, 1.59744711, 1.59744711, 1.59744711],
       [1.3614434 , 1.3614434 , 1.3614434 , 1.3614434 , 1.3614434 ],
       [1.78192408, 1.78192408, 1.78192408, 1.78192408, 1.78192408],
       [1.26456425, 1.26456425, 1.26456425, 1.26456425, 1.26456425],
       [1.07249806, 1.07249806, 1.07249806, 1.07249806, 1.07249806]])

In [32]:
matrice_5 = 4+np.ones((5,5))
matrice_5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])