In [16]:
import numpy as np
    #serve per manipolare array in maniera efficente

lista = [1,2,3,4]
array = np.array(lista)     #conversione lista in array
print(3*array)
print(3*lista)
print(10+array)

[ 3  6  9 12]
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
[11 12 13 14]


In [17]:
a = array.copy()
a

array([1, 2, 3, 4])

In [18]:
b = np.array(lista[::-1])
b

array([4, 3, 2, 1])

In [24]:
a+b

array([5, 5, 5, 5])

In [28]:
zeri = np.zeros(10,dtype=np.int8)    #zeri interi a 8 bit
zeri

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [29]:
uni = np.ones(10)
uni

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [82]:
np.random.uniform(1,2,10)

array([1.01304448, 1.76675022, 1.4620033 , 1.39515865, 1.12877574,
       1.39440758, 1.55477125, 1.38003473, 1.99105896, 1.7921882 ])