In [2]:
import numpy as np
a = np.linspace(0,10,3)
a

array([ 0.,  5., 10.])

In [10]:
np.linspace(0,10,3, dtype = np.int8)

array([ 0,  5, 10], dtype=int8)

In [28]:
ril = np.random.normal(19,5,1000)
#ril

In [29]:
arr = np.arange(0,1001)
#arr
err = np.random.choice((arr),20, replace=False)
err

array([264, 330, 707, 439, 122, 523, 498, 886, 756,  33, 411, 226,  66,
       942, 493, 510, 430, 769, 527, 783])

In [30]:
ril[err]=9999.9
ril

array([1.95367779e+01, 2.75910172e+01, 1.74308743e+01, 2.31136761e+01,
       1.99736823e+01, 1.71890328e+01, 1.75851542e+01, 2.77467631e+01,
       2.43156185e+01, 2.24121734e+01, 2.05721083e+01, 1.75882976e+01,
       2.29749853e+01, 2.50753708e+01, 6.49152655e+00, 2.15203720e+01,
       1.88563843e+01, 1.70859776e+01, 1.84081126e+01, 2.80250609e+01,
       1.82628249e+01, 2.05928382e+01, 2.60194314e+01, 2.08524433e+01,
       1.08731768e+01, 2.57962423e+01, 1.66175017e+01, 1.54798344e+01,
       2.46843679e+01, 8.51184930e+00, 1.62475308e+01, 2.19650051e+01,
       1.96105673e+01, 9.99990000e+03, 1.37905347e+01, 1.43348043e+01,
       2.50085202e+01, 2.10300743e+01, 1.98895363e+01, 1.78003148e+01,
       2.37327230e+01, 2.74321827e+01, 2.22415427e+01, 2.08892628e+01,
       2.11116331e+01, 1.97590644e+01, 2.21872007e+01, 2.17249380e+01,
       2.24231224e+01, 1.55259363e+01, 1.44802353e+01, 2.04708051e+01,
       2.96843158e+01, 2.03171742e+01, 1.36230793e+01, 1.18912767e+01,
      

In [36]:
%%timeit
a=np.random.seed(100)
a

2.14 µs ± 26.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [166]:
l=[1,1]
for i in range(2,10):
    x = l[i-1]+l[i-2]
    l.append(x)
a = np.array(l)

array([ 1,  1,  2,  3,  5,  8, 13, 21, 34, 55])

In [32]:
a = np.zeros(12, dtype=np.int8)
a[:2]=1
print(a)
a = [a[i-1]+a[i-2] for i in range(2,len(a))]
a

[1 1 0 0 0 0 0 0 0 0 0 0]


[2, 1, 0, 0, 0, 0, 0, 0, 0, 0]

In [19]:
scacchiera = np.array([[i for i in range(0,8)] for y in range(0,8)])
#scacchiera
contr=np.arange(0,8)
contr = contr[::-1]
scacchiera[::2]=contr
#scacchiera
scacchiera%2

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int32)